cart/urls.py
"""
Code adapted from the CI Boutique Ado mini project
"""

from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

fancy_shoes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
"""
Code adapted from the CI Boutique Ado mini project
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_page, name='product_page'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

checkout/models.py
"""
Code adapted from the CI Boutique Ado mini project
"""

import uuid
from django.db import models
from django_countries.fields import CountryField
from django.db.models import Sum
from django.conf import settings
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(
        max_length=32,
        null=False,
        editable=False)
    order_date = models.DateTimeField(
        auto_now_add=True)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders')
    first_name = models.CharField(
        max_length=50,
        null=False,
        blank=False)
    last_name = models.CharField(
        max_length=50,
        null=False,
        blank=False)
    email = models.EmailField(
        max_length=254,
        null=False,
        blank=False)
    telephone = models.CharField(
        max_length=20,
        null=False,
        blank=False)
    address_line1 = models.CharField(
        max_length=80,
        null=False,
        blank=False)
    address_line2 = models.CharField(
        max_length=80,
        null=True,
        blank=True)
    town_or_city = models.CharField(
        max_length=40,
        null=False,
        blank=False)
    county = models.CharField(
        max_length=80,
        null=True,
        blank=True)
    postcode = models.CharField(
        max_length=20,
        null=True,
        blank=True)
    country = CountryField(
        blank_label='Country *',
        null=False,
        blank=False)
    delivery_cost = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        default=0)
    order_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0)
    grand_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        default=0)
    original_cart = models.TextField(
        null=False,
        blank=False,
        default='')
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            sdp = settings.STANDARD_DELIVERY_PERCENTAGE
            self.delivery_cost = self.order_total * sdp / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order
        number if it hasn't already been set.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save()

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems')
    product = models.ForeignKey(
        Product,
        null=False,
        blank=False,
        on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2,
        null=True,
        blank=True)
    quantity = models.IntegerField(
        null=False,
        blank=False,
        default=0)
    lineitem_total = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order
        number if it hasn't already been set.
        """
        self.lineitem_total = self.product.discount_price * self.quantity
        super().save()

    def __str__(self):
        return f'Code {self.product.sku} on order {self.order.order_number}'

products/models.py
"""
Code adapted from the CI Boutique Ado mini project
"""

from django.db import models


class Gender(models.Model):
    """
    Model Gender allows the grouping of product
    for easier searches
    """
    name = models.CharField(
        max_length=254)
    display_name = models.CharField(
        max_length=254)

    def __str__(self):
        return self.name

    def gender_display_name(self):
        return self.display_name


class ArticleType(models.Model):
    """
    Model ArticleType allows the grouping of products
    for easier searches by type of item or product
    """
    name = models.CharField(
        max_length=254)
    display_name = models.CharField(
        max_length=254)

    def __str__(self):
        return self.name

    def article_type_display_name(self):
        return self.display_name


class Category(models.Model):
    """
    Model Category allows the grouping of products
    for easier searches by category of item or product
    """
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(
        max_length=254)
    display_name = models.CharField(
        max_length=254)

    def __str__(self):
        return self.name

    def category_display_name(self):
        return self.display_name


class SubCategory(models.Model):
    """
    Model SubCategory allows the grouping of products
    for easier searches by sub-category of item or product
    """

    class Meta:
        verbose_name_plural = 'Sub Categories'

    name = models.CharField(
        max_length=254)
    display_name = models.CharField(
        max_length=254)

    def __str__(self):
        return self.name

    def sub_category_display_name(self):
        return self.display_name


class SpecialOffer(models.Model):
    """
    Model SpecialOffers allows the grouping of products
    for easier searches by adding an extra special offer category
    """
    name = models.CharField(
        max_length=254)
    display_name = models.CharField(
        max_length=254)

    def __str__(self):
        return self.name

    def special_offer_display_name(self):
        return self.display_name


class Product(models.Model):
    """
    Model Product contains the detailed product information
    with foreign keys to the related category models
    """

    price = models.DecimalField(
        max_digits=6,
        decimal_places=2)
    discount_price = models.DecimalField(
        max_digits=6,
        decimal_places=2)
    sku = models.CharField(
        max_length=254)
    name = models.CharField(
        max_length=254)
    product_description = models.TextField()
    colour = models.CharField(
        max_length=254)
    sizes = models.BooleanField(
        default=False,
        null=True,
        blank=True)
    gender = models.ForeignKey(
        'Gender',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    category = models.ForeignKey(
        'Category',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    sub_category = models.ForeignKey(
        'SubCategory',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    article_type = models.ForeignKey(
        'ArticleType',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    special_offer = models.ForeignKey(
        'SpecialOffer',
        null=True,
        blank=True,
        on_delete=models.SET_NULL)
    image = models.ImageField(
        blank=True,
        null=True)

    def __str__(self):
        return self.name

products/forms.py
"""
Code adapted from the CI Boutique Ado mini project
"""

from django import forms
from .widgets import CustomClearableFileInput
from .models import (
    Product, Gender, ArticleType, Category, SubCategory, SpecialOffer)


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(
        label='Image',
        required=False,
        widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        gender = Gender.objects.all()
        article_type = ArticleType.objects.all()
        category = Category.objects.all()
        sub_category = SubCategory.objects.all()
        special_offer = SpecialOffer.objects.all()
        gender_display_name = [(
            g.id,
            g.gender_display_name()
        ) for g in gender]
        article_type_display_name = [(
            at.id,
            at.article_type_display_name()
        ) for at in article_type]
        category_display_name = [(
            c.id,
            c.category_display_name()
        ) for c in category]
        sub_category_display_name = [(
            sc.id,
            sc.sub_category_display_name()
        ) for sc in sub_category]
        special_offer_display_name = [(
            so.id,
            so.special_offer_display_name()
        ) for so in special_offer]

        self.fields['gender'].choices = gender_display_name
        self.fields['article_type'].choices = article_type_display_name
        self.fields['category'].choices = category_display_name
        self.fields['sub_category'].choices = sub_category_display_name
        self.fields['special_offer'].choices = special_offer_display_name
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border rounded-0'

products/views.py
"""
Code adapted from the CI Boutique Ado mini project
"""

from django.shortcuts import (
    render, redirect, reverse, get_object_or_404)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import (
    Product, Gender, Category, SubCategory, ArticleType, SpecialOffer)
from .forms import ProductForm


def all_products(request):
    """
    A view to show all products, including sorting and search queries
    """

    products = Product.objects.all()
    sort = None
    direction = None
    query = None
    gender = None
    category = None
    sub_category = None
    article_type = None
    special_offer = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'gender' in request.GET:
            gender = request.GET['gender'].split(',')
            products = products.filter(
                gender__name__in=gender)
            gender = Gender.objects.filter(
                name__in=gender)

        if 'category' in request.GET:
            category = request.GET['category'].split(',')
            products = products.filter(
                category__name__in=category)
            category = Category.objects.filter(
                name__in=category)

        if 'sub_category' in request.GET:
            sub_category = request.GET['sub_category'].split(',')
            products = products.filter(
                sub_category__name__in=sub_category)
            sub_category = SubCategory.objects.filter(
                name__in=sub_category)

        if 'article_type' in request.GET:
            article_type = request.GET['article_type'].split(',')
            products = products.filter(
                article_type__name__in=article_type)
            article_type = ArticleType.objects.filter(
                name__in=article_type)

        if 'special_offer' in request.GET:
            special_offer = request.GET['special_offer'].split(',')
            products = products.filter(
                special_offer__name__in=special_offer)
            special_offer = SpecialOffer.objects.filter(
                name__in=special_offer)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter a search criteria")
                return redirect(reverse('products'))

            queries = (
                Q(name__icontains=query) |
                Q(product_description__icontains=query) |
                Q(gender__name__icontains=query) |
                Q(category__name__icontains=query) |
                Q(sub_category__name__icontains=query) |
                Q(article_type__name__icontains=query) |
                Q(special_offer__name__icontains=query))
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'
    context = {
        'products': products,
        'search_term': query,
        'current_gender': gender,
        'current_category': category,
        'current_sub_category': sub_category,
        'current_article_type': article_type,
        'current_special_offer': special_offer,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_page(request, product_id):
    """
    A view to show individual product details
    """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_page.html', context)


@login_required
def add_product(request):
    """
    Add a product to the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    # form post handler
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_page', args=[product.id]))
        else:
            messages.error(request,
                           ('Failed to add product. '
                            'Please ensure the form is valid.'))
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """
    Edit a product in the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)

    # form post handler
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_page', args=[product.id]))
        else:
            messages.error(request,
                           ('Failed to update product. '
                            'Please ensure the form is valid.'))
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete a product from the store
    """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
<!-- Code adapted from CI Boutique Ado mini project -->

{% extends "base.html" %}
{% load static %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-white small pl-0 pl-sm-3">

        <!-- Home Link -->
        <li class="breadcrumb-item">
            <a href="{% url 'home' %}">
                Home
            </a>
        </li>

        <!-- All Products link -->
        <li class="breadcrumb-item">
            <a href="{% url 'products' %}">
                Products
            </a>
        </li>

        <!-- Product Management -->
        <li class="breadcrumb-item" aria-current="page">
            Product Management
        </li>

        <!-- Add a Product -->
        <li class="breadcrumb-item active" aria-current="page">
            Add a Product
        </li>
    </ol>
</nav>
{% endblock %}


{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <!-- Page Title -->
    <div class="row">
        <div class="col-12 col-md-6">            
            <h2 class="logo-font">Product Management</h2>
            <h5 class="text-muted">Add a Product</h5>
            <hr>
        </div>
    </div>

    <!-- Add product form -->
    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right mb-4">
                    <a class="btn btn-outline-danger btn-lg" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-outline-success btn-lg" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<!-- Image update functionality -->
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_page.html
<!-- Code adapted from CI Boutique Ado mini project -->

{% extends "base.html" %}
{% load static %}

{% block extra_title %}All the shoes you want!{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-white small pl-0 pl-sm-3">

        <!-- Home Link -->
        <li class="breadcrumb-item">
            <a href="{% url 'home' %}">
                Home
            </a>
        </li>

        <!-- All Products link -->
        <li class="breadcrumb-item">
            <a href="{% url 'products' %}">
                Products
            </a>
        </li>

        <!-- Gender filtering -->
        <li class="breadcrumb-item">
            <a
                href="{% url 'products' %}?gender={{ product.gender.name }}">
                {{ product.gender.display_name }}                
            </a>
        </li>

        <!-- Product Category filtering -->
        <li class="breadcrumb-item">
            <a
                href="{% url 'products' %}?gender={{ product.gender.name }}&sub_category={{ product.sub_category.name }}">                
                {{ product.sub_category.display_name }}
            </a>
        </li>

        <!-- Product Type filtering -->
        <li class="breadcrumb-item">
            <a
                href="{% url 'products' %}?gender={{ product.gender.name }}&article_type={{ product.article_type.name }}">
                {{ product.article_type.display_name }}
            </a>
        </li>

        <!-- Product Display Name -->
        <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
    </ol>
</nav>
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid mb-3">
    <div class="row">

        <!-- Product Image Container -->
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container">

                <!-- Display the product image -->
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" width="600" height="450" src="{{ product.image.url }}"
                        alt="{{ product.name }}">
                </a>
                {% else %}

                <!-- Else display the default "No Image" placeholder file -->
                <a href="">
                    <img class="card-img-top img-fluid" width="600" height="450" src="{{ MEDIA_URL }}noimage.png"
                        alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>

        <!-- Product Details Section -->
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product_page_container mb-5 mt-md-5">

                <!-- Product Name -->
                <h3 class="mb-0">
                    {{ product.name }}
                </h3>

                <!-- Product RRP & Discount Prices -->
                <p>
                    <span class="lead mb-0 text-left text-danger font-weight-bold">
                        £{{ product.discount_price }}
                    </span>
                    <span class="text-muted">
                        RRP <span class="strike-through-text">£{{ product.price }}</span>
                    </span>
                </p>

                <!-- Product Category -->
                {% if product.sub_category %}
                <p class="small mt-1 mb-0">
                    <a href="{% url 'products' %}?sub_category={{ products.sub_category.name }}" 
                      class="text-muted">
                        <i class="fas fa-tag mr-1"></i>{{ product.sub_category.display_name }}
                    </a>
                </p>
                {% endif %}

                <!-- Super User product edit & delete links -->
                {% if request.user.is_superuser %}
                <p class="mt-3 mb-0">
                    <small>
                        <a class="btn btn-outline-info mr-2" 
                          href="{% url 'edit_product' product.id %}">
                            <i class="fas fa-edit fa-sm"></i>
                            Edit
                        </a>
                        <a class="btn btn-outline-danger" 
                          href="{% url 'delete_product' product.id %}">
                            <i class="far fa-trash-alt fa-sm"></i>
                            Delete
                        </a>
                    </small>
                </p>
                {% endif %}

                <!-- Product Description -->
                <p class="mt-3">
                    {{ product.product_description }}
                </p>

                <!-- Product Colour -->
                <p class="mt-3">
                    <strong>Colour:</strong><br>
                    {{ product.colour }}
                </p>

                <!-- Add to Shopping Cart qty selector & buttons -->
                <form action="{% url 'add_to_cart' product.id %}" class="form" method="POST">
                    {% csrf_token %}

                    <!-- Item size & quantity selectors -->
                    <div class="form-row">
                        
                        <!-- Shoe sizes -->                        
                        <div class="col-12">
                            <p class="mb-1"><strong>Size:</strong></p>
                            <select class="border p-2" name="product_size" id="id_product_size" 
                              class="form-control rounded-0 w-25">
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9" selected>9</option>
                                <option value="9.5">9.5</option>
                                <option value="10">10</option>
                                <option value="10.5">10.5</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                            </select>
                        </div>
                        
                        <!-- Quantity Selector -->
                        <div class="col-12">
                            <p class="mt-3 mb-1"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <!-- minus button -->
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-outline-dark rounded-0"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}"
                                            aria-label="decrease quantity">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <!-- Qty input field -->
                                    <input class="form-control qty_input text-center border" type="number" name="quantity"
                                        value="1" min="1" max="99" data-item_id="{{ product.id }}"
                                        id="id_qty_{{ product.id }}" aria-label="quantity input" required>
                                    <!-- plus button -->
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-outline-dark rounded-0"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}"
                                            aria-label="increase quantity">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Keep Shopping & Add to Cart Buttons -->
                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn btn-outline-blue btn-lg mt-5">
                                <i class="fas fa-shopping-bag fa-sm"></i> 
                                Keep Shopping
                            </a>
                            <input type="submit" class="btn btn-outline-success btn-lg text-uppercase mt-5"
                                value="Add to Shopping Cart">
                        </div>

                        <!-- Redirects user back to product page after item added to shopping cart -->
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">                        
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}